apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: version-a-deployment  
spec:  
  replicas: 2  
  selector:  
    matchLabels:  
      app: ab-testing
      environment: version-a
  template:  
    metadata:  
      labels:  
        app: ab-testing  
        environment: version-a  
    spec:  
      containers:  
        - name: nginx  
          image: linuxacademycontent/ckad-nginx:1.0.0  
          ports:  
            - containerPort: 80
