apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: version-b-deployment  
spec:  
  replicas: 2 
  selector:  
    matchLabels:  
      app: ab-testing  
      environment: version-b  
  template:  
    metadata:  
      labels:  
        app: ab-testing 
        environment: version-b  
    spec:  
      containers:  
        - name: nginx  
          image: linuxacademycontent/ckad-nginx:canary
          ports:  
            - containerPort: 80
